// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/account.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/account.go -destination=internal/handler/mocks/account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/funkymotions/go-ya-practicum-diploma/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
	isgomock struct{}
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// CalculateAccountBalance mocks base method.
func (m *MockAccountService) CalculateAccountBalance(userID uint) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAccountBalance", userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CalculateAccountBalance indicates an expected call of CalculateAccountBalance.
func (mr *MockAccountServiceMockRecorder) CalculateAccountBalance(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAccountBalance", reflect.TypeOf((*MockAccountService)(nil).CalculateAccountBalance), userID)
}

// WithdrawFromAccount mocks base method.
func (m *MockAccountService) WithdrawFromAccount(userID uint, data *dto.AccountBalanceWithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawFromAccount", userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawFromAccount indicates an expected call of WithdrawFromAccount.
func (mr *MockAccountServiceMockRecorder) WithdrawFromAccount(userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawFromAccount", reflect.TypeOf((*MockAccountService)(nil).WithdrawFromAccount), userID, data)
}
