// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/account.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/account.go -destination=internal/handler/mocks/account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/funkymotions/go-ya-practicum-diploma/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountService is a mock of accountService interface.
type MockaccountService struct {
	ctrl     *gomock.Controller
	recorder *MockaccountServiceMockRecorder
	isgomock struct{}
}

// MockaccountServiceMockRecorder is the mock recorder for MockaccountService.
type MockaccountServiceMockRecorder struct {
	mock *MockaccountService
}

// NewMockaccountService creates a new mock instance.
func NewMockaccountService(ctrl *gomock.Controller) *MockaccountService {
	mock := &MockaccountService{ctrl: ctrl}
	mock.recorder = &MockaccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountService) EXPECT() *MockaccountServiceMockRecorder {
	return m.recorder
}

// CalculateAccountBalance mocks base method.
func (m *MockaccountService) CalculateAccountBalance(userID uint) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAccountBalance", userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CalculateAccountBalance indicates an expected call of CalculateAccountBalance.
func (mr *MockaccountServiceMockRecorder) CalculateAccountBalance(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAccountBalance", reflect.TypeOf((*MockaccountService)(nil).CalculateAccountBalance), userID)
}

// WithdrawFromAccount mocks base method.
func (m *MockaccountService) WithdrawFromAccount(userID uint, data *dto.AccountBalanceWithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawFromAccount", userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawFromAccount indicates an expected call of WithdrawFromAccount.
func (mr *MockaccountServiceMockRecorder) WithdrawFromAccount(userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawFromAccount", reflect.TypeOf((*MockaccountService)(nil).WithdrawFromAccount), userID, data)
}
