// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/order.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/order.go -destination=internal/handler/mocks/order.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	sync "sync"

	dto "github.com/funkymotions/go-ya-practicum-diploma/internal/dto"
	model "github.com/funkymotions/go-ya-practicum-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// EnqueueOrdersFromAccrualSystem mocks base method.
func (m *MockOrderService) EnqueueOrdersFromAccrualSystem(arg0 context.Context, arg1 *sync.WaitGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueOrdersFromAccrualSystem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueOrdersFromAccrualSystem indicates an expected call of EnqueueOrdersFromAccrualSystem.
func (mr *MockOrderServiceMockRecorder) EnqueueOrdersFromAccrualSystem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueOrdersFromAccrualSystem", reflect.TypeOf((*MockOrderService)(nil).EnqueueOrdersFromAccrualSystem), arg0, arg1)
}

// GetUserOrders mocks base method.
func (m *MockOrderService) GetUserOrders(userID uint) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", userID)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderServiceMockRecorder) GetUserOrders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderService)(nil).GetUserOrders), userID)
}

// ProcessOrderFromAccrual mocks base method.
func (m *MockOrderService) ProcessOrderFromAccrual(order *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOrderFromAccrual", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOrderFromAccrual indicates an expected call of ProcessOrderFromAccrual.
func (mr *MockOrderServiceMockRecorder) ProcessOrderFromAccrual(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrderFromAccrual", reflect.TypeOf((*MockOrderService)(nil).ProcessOrderFromAccrual), order)
}

// RegisterOrder mocks base method.
func (m *MockOrderService) RegisterOrder(arg0 *dto.RegisterOrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockOrderServiceMockRecorder) RegisterOrder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockOrderService)(nil).RegisterOrder), arg0)
}
