// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/withdrawal.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/withdrawal.go -destination=internal/handler/mocks/withdrawal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/funkymotions/go-ya-practicum-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockwithdrawalService is a mock of withdrawalService interface.
type MockwithdrawalService struct {
	ctrl     *gomock.Controller
	recorder *MockwithdrawalServiceMockRecorder
	isgomock struct{}
}

// MockwithdrawalServiceMockRecorder is the mock recorder for MockwithdrawalService.
type MockwithdrawalServiceMockRecorder struct {
	mock *MockwithdrawalService
}

// NewMockwithdrawalService creates a new mock instance.
func NewMockwithdrawalService(ctrl *gomock.Controller) *MockwithdrawalService {
	mock := &MockwithdrawalService{ctrl: ctrl}
	mock.recorder = &MockwithdrawalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwithdrawalService) EXPECT() *MockwithdrawalServiceMockRecorder {
	return m.recorder
}

// GetUserWithdrawals mocks base method.
func (m *MockwithdrawalService) GetUserWithdrawals(userID uint) (*[]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", userID)
	ret0, _ := ret[0].(*[]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockwithdrawalServiceMockRecorder) GetUserWithdrawals(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockwithdrawalService)(nil).GetUserWithdrawals), userID)
}
