// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/account.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/account.go -destination=internal/service/mocks/account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
