// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/order.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/order.go -destination=internal/service/mocks/order.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	sync "sync"

	dto "github.com/funkymotions/go-ya-practicum-diploma/internal/dto"
	model "github.com/funkymotions/go-ya-practicum-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// EnqueueOrdersFromAccrualSystem mocks base method.
func (m *MockOrderService) EnqueueOrdersFromAccrualSystem(arg0 context.Context, arg1 *sync.WaitGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueOrdersFromAccrualSystem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueOrdersFromAccrualSystem indicates an expected call of EnqueueOrdersFromAccrualSystem.
func (mr *MockOrderServiceMockRecorder) EnqueueOrdersFromAccrualSystem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueOrdersFromAccrualSystem", reflect.TypeOf((*MockOrderService)(nil).EnqueueOrdersFromAccrualSystem), arg0, arg1)
}

// GetUserOrders mocks base method.
func (m *MockOrderService) GetUserOrders(userID uint) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", userID)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderServiceMockRecorder) GetUserOrders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderService)(nil).GetUserOrders), userID)
}

// ProcessOrderFromAccrual mocks base method.
func (m *MockOrderService) ProcessOrderFromAccrual(order *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOrderFromAccrual", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOrderFromAccrual indicates an expected call of ProcessOrderFromAccrual.
func (mr *MockOrderServiceMockRecorder) ProcessOrderFromAccrual(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrderFromAccrual", reflect.TypeOf((*MockOrderService)(nil).ProcessOrderFromAccrual), order)
}

// RegisterOrder mocks base method.
func (m *MockOrderService) RegisterOrder(arg0 *dto.RegisterOrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockOrderServiceMockRecorder) RegisterOrder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockOrderService)(nil).RegisterOrder), arg0)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(orderID string, userID uint) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", orderID, userID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), orderID, userID)
}

// FindManyByStatus mocks base method.
func (m *MockOrderRepository) FindManyByStatus(statuses ...model.OrderStatus) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range statuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindManyByStatus", varargs...)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindManyByStatus indicates an expected call of FindManyByStatus.
func (mr *MockOrderRepositoryMockRecorder) FindManyByStatus(statuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindManyByStatus", reflect.TypeOf((*MockOrderRepository)(nil).FindManyByStatus), statuses...)
}

// FindOneByID mocks base method.
func (m *MockOrderRepository) FindOneByID(id string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", id)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockOrderRepositoryMockRecorder) FindOneByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockOrderRepository)(nil).FindOneByID), id)
}

// GetUserOrderBalance mocks base method.
func (m *MockOrderRepository) GetUserOrderBalance(userID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderBalance", userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderBalance indicates an expected call of GetUserOrderBalance.
func (mr *MockOrderRepositoryMockRecorder) GetUserOrderBalance(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderBalance", reflect.TypeOf((*MockOrderRepository)(nil).GetUserOrderBalance), userID)
}

// GetUserOrders mocks base method.
func (m *MockOrderRepository) GetUserOrders(userID uint) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", userID)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderRepositoryMockRecorder) GetUserOrders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetUserOrders), userID)
}

// UpdateOrder mocks base method.
func (m *MockOrderRepository) UpdateOrder(order *model.Order) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", order)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrder), order)
}
