// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/order.go -destination=internal/service/mocks/order.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/funkymotions/go-ya-practicum-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockorderRepository is a mock of orderRepository interface.
type MockorderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockorderRepositoryMockRecorder
	isgomock struct{}
}

// MockorderRepositoryMockRecorder is the mock recorder for MockorderRepository.
type MockorderRepositoryMockRecorder struct {
	mock *MockorderRepository
}

// NewMockorderRepository creates a new mock instance.
func NewMockorderRepository(ctrl *gomock.Controller) *MockorderRepository {
	mock := &MockorderRepository{ctrl: ctrl}
	mock.recorder = &MockorderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepository) EXPECT() *MockorderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockorderRepository) CreateOrder(orderID string, userID uint) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", orderID, userID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockorderRepositoryMockRecorder) CreateOrder(orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockorderRepository)(nil).CreateOrder), orderID, userID)
}

// FindOneByID mocks base method.
func (m *MockorderRepository) FindOneByID(id string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", id)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockorderRepositoryMockRecorder) FindOneByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockorderRepository)(nil).FindOneByID), id)
}

// GetUserOrderBalance mocks base method.
func (m *MockorderRepository) GetUserOrderBalance(userID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderBalance", userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderBalance indicates an expected call of GetUserOrderBalance.
func (mr *MockorderRepositoryMockRecorder) GetUserOrderBalance(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderBalance", reflect.TypeOf((*MockorderRepository)(nil).GetUserOrderBalance), userID)
}

// GetUserOrders mocks base method.
func (m *MockorderRepository) GetUserOrders(userID uint) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", userID)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockorderRepositoryMockRecorder) GetUserOrders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockorderRepository)(nil).GetUserOrders), userID)
}
