// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/withdrawal.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/withdrawal.go -destination=internal/service/mocks/withdrawal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/funkymotions/go-ya-practicum-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockwithdrawalRepository is a mock of withdrawalRepository interface.
type MockwithdrawalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockwithdrawalRepositoryMockRecorder
	isgomock struct{}
}

// MockwithdrawalRepositoryMockRecorder is the mock recorder for MockwithdrawalRepository.
type MockwithdrawalRepositoryMockRecorder struct {
	mock *MockwithdrawalRepository
}

// NewMockwithdrawalRepository creates a new mock instance.
func NewMockwithdrawalRepository(ctrl *gomock.Controller) *MockwithdrawalRepository {
	mock := &MockwithdrawalRepository{ctrl: ctrl}
	mock.recorder = &MockwithdrawalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwithdrawalRepository) EXPECT() *MockwithdrawalRepositoryMockRecorder {
	return m.recorder
}

// CreateWithdrawal mocks base method.
func (m *MockwithdrawalRepository) CreateWithdrawal(userID uint, orderID string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockwithdrawalRepositoryMockRecorder) CreateWithdrawal(userID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockwithdrawalRepository)(nil).CreateWithdrawal), userID, orderID, amount)
}

// GetUserWithdrawalBalance mocks base method.
func (m *MockwithdrawalRepository) GetUserWithdrawalBalance(userID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawalBalance", userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawalBalance indicates an expected call of GetUserWithdrawalBalance.
func (mr *MockwithdrawalRepositoryMockRecorder) GetUserWithdrawalBalance(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawalBalance", reflect.TypeOf((*MockwithdrawalRepository)(nil).GetUserWithdrawalBalance), userID)
}

// GetUserWithdrawals mocks base method.
func (m *MockwithdrawalRepository) GetUserWithdrawals(userID uint) (*[]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", userID)
	ret0, _ := ret[0].(*[]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockwithdrawalRepositoryMockRecorder) GetUserWithdrawals(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockwithdrawalRepository)(nil).GetUserWithdrawals), userID)
}
